# Generated by Django 3.1.6 on 2021-02-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='very cool hotel!'),
        ),
    ]
